### ISSUE TITLE
NON api import 

### ISSUE THREAD

**Issue by gigabit101** [Darkhax-Minecraft/Tesla#13]
https://github.com/Darkhax-Minecraft/Tesla/blob/master/src/main/java/net/darkhax/tesla/api/package-info.java#L4

**Comment by Darkhax** [comment]
While this would be an easy fix, I may drop support for Forge's API system. This API system was a workaround created to allow mods to bundle the API of other mods. It is incredibly bad practice to bundle foreign APIs with your project so I am kind of confused why Forge even provides this.

**Comment by p455w0rd** [comment]
Gotta go with logic on this one..
