### ISSUE TITLE
(Question) ITeslaItem

### ISSUE THREAD

**Issue by gigabit101** [Darkhax-Minecraft/Tesla#14]
Do you plan on adding a Item interface for powered Items like battery and tools ?

**Comment by Darkhax** [comment]
Capabilities can be attached to Entities, TileEntities and ItemStacks which already covers this feature. Using capabilities over a new interface allows for universal interactions between all three. If capabilities are not a viable approach to item support then I will open up further discussion.

**Comment by p455w0rd** [comment]
yeah..okay Lex, give DH his account back XD

**Comment by asiekierka** [comment]
@p455w0rd Charset uses ItemStack capabilities

**Comment by p455w0rd** [comment]
I was just messing with him..since I finally got RF working on my TileEntities today, I'll be implementing capabilities in my mod as much as possible.

**Comment by Darkhax** [comment]
Issue is closed, but if anyone wants to continue discussing here feel free.
