### ISSUE TITLE
Add More Utilities To Tesla

### ISSUE THREAD

**Issue by adrwa** [Darkhax-Minecraft/Tesla#23]
_This issue is intended as a discussion_

Should more utilities like the powerbar be added to Tesla

Some ideas of utilities are,
- Item Powerbar Rendering Helper
- IEmpowerableItem interface

**Comment by Prospector** [comment]
YES

**Comment by knoxhack** [comment]
Some of these types of utilities would be helpful if posibble.
https://github.com/CoFH/CoFHCore/tree/master/src/main/java/cofh/core
https://github.com/CoFH/CoFHLib
https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/item/tool/ItemToolAdv.java
https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/api/block/IDismantleable.java
https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/api/item/IEmpowerableItem.java

**Comment by Prospector** [comment]
I second the IEmpowerableItem, however I don't think ItemToolAdv is necessary because each mod will probably have tools that work differently. Maybe just me though. Then again, it's not like mods have to use the class, they could just add their own.

**Comment by ZeroNoRyouki** [comment]
I would say no. Keep the API slim, easy to update, and with only the content that is really needed by all mods that use Tesla

A collection of utilities could probably go into another small mod

**Comment by adrwa** [comment]
@ZeroNoRyouki The problem with an external small mod, people wouldn't add compatibility for it, plus if it fits into tesla's theme, why not, but in the end it is whatever darkhax decides

**Comment by adrwa** [comment]
@ProfessorProspector I second IEmpowerableItem too, but IDismantleable im not sure if i see how it fits into tesla

**Comment by Prospector** [comment]
True, IDismantleable doesn't make sense :P

**Comment by Prospector** [comment]
@ZeroNoRyouki Which is slimmer, Tesla adding utils that almost every single mod using tesla will use, or each of those mods adding the utils individually?

**Comment by adrwa** [comment]
Using the PowerBar as an example, i've gotten only good feedback about that being implemented into tesla

**Comment by ZeroNoRyouki** [comment]
@ProfessorProspector : an API-only Tesla mod (like the current one) and a common-utilities mod with GUI stuff and such that mod can use if they need it (not all mods that use Tesla will use it)

@TheCodedOne : compatibility? This is basically a small library of code. If I need it for my mod I will use it, not be compatible with it. I'm not saying that the PowerBar is a bad idea (though I will not implement it using capabs), I'll just not add it to Tesla because not all mods that use Tesla will use it

**Comment by Prospector** [comment]
Name 2 mods that use tesla and don't have tesla power bars in a gui

**Comment by adrwa** [comment]
@ZeroNoRyouki this stuff we're discussing isnt meant to target everyone, some people might want to do it their own way, which is fine they have free will, it is designed for the newer modders who dont know as much as some of the more experienced modders to be able to have something that looks good and functions well, while being able for them to learn how it works through the source code.

**Comment by ZeroNoRyouki** [comment]
@ProfessorProspector: Mods that don't have a GUI (say, blocks like EnderIO power banks that display the charge level on the block itself), or ones that have their own power bars

@TheCodedOne: well, if it's not for everyone why put it in the main API then?

Dont' get me wrong guys, I think this is really a good idea. I just will not put it in the main API

**Comment by adrwa** [comment]
@ZeroNoRyouki enderio has got GUI's for the powerbanks you know.. that do show the power level inside them

**Comment by adrwa** [comment]
![](http://wiki.enderio.com/images/CapBankGUI.png)

**Comment by ZeroNoRyouki** [comment]
@TheCodedOne : yeah I know, but the main function of that GUI is to set the I/O rates and recharge stuff. Take that away and you would not need a GUI (and power bar) at all

**Comment by Prospector** [comment]
yo you be rustlin @TheCodedOne's jimmies and gettin him all mad and shit. he'd like you to not respond again. thank you for contacting TESLA customer service. make sure 2 give me 6 star rating and 100$ pls. thank u come again,.

**Comment by ZeroNoRyouki** [comment]
lol

**Comment by Rushmead** [comment]
Personally, I feel as if adding things like a Powerbar will be super beneficial because i don't know that much about modding so adding powerbars is difficult for me. #VoteAddUtils

**Comment by Prospector** [comment]
#VoteAddUtils #VoteTrump

**Comment by adrwa** [comment]
#BuildTheWall

**Comment by adrwa** [comment]
Currently, i will work on 2 separate Pull requests
- The Item Powerbar Rendering Helper
- The IEmpowerableItem interface

**Comment by gigabit101** [comment]
@TheCodedOne why is this needed its simple to do those things https://github.com/CrystekTeam/Crystek/blob/master/src/main/java/crystekteam/crystek/items/ItemTeslaBase.java

**Comment by Darkhax** [comment]
@ZeroNoRyouki and everyone else: The reason Tesla is a full on mod and not an API is so it can provide additional functionality that isn't included with a traditional API. Some current examples of this include the automatic initialization of the capabilities, several capability based utilities, unit conversion, and thanks to @TheCodedOne power bar rendering. I am definitely fine with giving mod authors the tools to do common things, this ensures that the code being used is efficient and reliable, it also makes things easier for newer developers.

**Comment by adrwa** [comment]
If there arent any more ideas i'll close this.
