### ISSUE TITLE
1.9.4/1.10.2 Compatible version

### ISSUE THREAD

**Issue by Keridos** [Darkhax-Minecraft/Tesla#26]
If your mod compiles on both platforms you can run the with forge for 1.10.2 compiled mod on 1.9.4 as well, as long as you set acceptedMinecraftVersions to "[1.9.4,1.10.2]" in your `@Mod` Annotation.

So, could you consider just adding that to Tesla and just release a backwards compatible version on curseforge?

**Comment by Darkhax** [comment]
Fixed in https://github.com/Darkhax-Minecraft/Tesla/commit/5539b933ec0770379db2ad70c26c0fec8ad7f0ec
