### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by vrork** [Darkhax-Minecraft/Tesla#28]
Hello! I am having a crash on my modpack with tesla

Crash report
http://pastebin.com/hhFFLnt4

**Comment by Rushmead** [comment]
Have you put the tesla mod inside your mods folder?

**Comment by vrork** [comment]
Yes

**Comment by gigabit101** [comment]
TeslaArsanal needs to update to new api

**Comment by Darkhax** [comment]
TeslaArsenal needs to update to the latest API. The code they are using was marked as deprecated on June 10th.

**Comment by knoxhack** [comment]
Fixed: https://github.com/knoxhack/Tesla-Arsenal/commit/28c81d4319c55936544a14476a8c94d134a407c2
