### ISSUE TITLE
Inconsistent modid between mcmod.info and inside mod class

### ISSUE THREAD

**Issue by zlainsama** [Darkhax-Minecraft/Tesla#29]
MinecraftForge/MinecraftForge@45b299ce06a453debe31c7056441d2aff26106e1

lowercasing will be enforced in future.

**Comment by zlainsama** [comment]
in mcmod.info, the modid is in lowercase.
but in the mod class, the modid is not.
this will cause a check for "tesla:any" fails.

**Comment by Darkhax** [comment]
Thank you for pointing this out.

**Comment by Darkhax** [comment]
Closed by https://github.com/Darkhax-Minecraft/Tesla/commit/69f27fc3e225138c06390716e9ed1b19f36c74be
