### ISSUE TITLE
Peta Prefix

### ISSUE THREAD

**Issue by N9199** [Darkhax-Minecraft/Tesla#31]
I'm assuming that the standard that's been used is the IS prefixes, and based on that assumption one of the prefixes on the .lang files is wrong, it's not "penta" it "peta".

**Comment by Darkhax** [comment]
You are correct, this is a typo. This will be fixed for the next release.

**Comment by Darkhax** [comment]
Fixed in 0b5f5c5fcdb4e6a7ca3c288b075bc141f1811cbc
