### ISSUE TITLE
Wrong Capability in TeslaUtils

### ISSUE THREAD

**Issue by canitzp** [Darkhax-Minecraft/Tesla#38]
The methods [getTeslaConsumer](https://github.com/Darkhax-Minecraft/Tesla/blob/master/src/main/java/net/darkhax/tesla/lib/TeslaUtils.java#L191) and [getTeslaProducer](https://github.com/Darkhax-Minecraft/Tesla/blob/master/src/main/java/net/darkhax/tesla/lib/TeslaUtils.java#L203) are getting the wrong capability from the CapabilityProvider. They should use CAPABILITY_CONSUMER and CAPABILITY_PRODUCER instead of CAPABILITY_HOLDER

**Comment by Darkhax** [comment]
Thank you for reporting this. Will have a fix out promptly.

**Comment by Darkhax** [comment]
Fixed in https://github.com/Darkhax-Minecraft/Tesla/commit/fb792395fdda6793cfbe4482dfdc49f881d3be75 new [release](https://minecraft.curseforge.com/projects/tesla/files/2327384) is pushed.
