### ISSUE TITLE
Rebrand the project.

### ISSUE THREAD

**Issue by Darkhax** [Darkhax-Minecraft/Tesla#4]
Several people have complained about the name of the project. The following is a list of issues people have with it. 
- RotaryCraft already uses Tesla as a unit of measurement in some of it's systems.
- Tesla is a real unit of measurement that is unrelated to power. 
- Tesla uses the abbreviation of T which might confuse people. 

Looking for feedback on whether or not the name should be changed, and possible name replacements. If you do not think that the project needs rebranding, please thumb down this issue.

**Comment by iLexiconn** [comment]
_Darkm4tter_

**Comment by Fortanono** [comment]
Well, how about Cubic Watts? W3 could be the abbreviation, and it sounds Minecrafty like Redstone Flux.

**Comment by Darkhax** [comment]
@Fortanono I think that Cubic Watts would have similar confusion issues because of the number. 133W3/t and such.

**Comment by Fortanono** [comment]
Maybe we could use a small 3, as in cubic centimeters?

**Comment by iLexiconn** [comment]
And maybe change it to /s?

**Comment by brandon3055** [comment]
The problem is all of the good names have already been taken. Watts or joules would be great but they are already used.
The only good one i can think of is VA (Volt-Amps) Which is basically a measurement of AC watts.

**Comment by Sethgoldfox** [comment]
I think that Tesla is a perfect name (Doesn't have to be realistic at all). Also don't think that Reika would be immature enough to throw a fit over something like a name.

**Comment by Fortanono** [comment]
I guess that is true. Volts wouldn't be scientifically correct, but it could work. Have another name that isn't scientifically correct, too: pA (Pickamps).

**Comment by Darkhax** [comment]
@Fortanono The issue with a small 3 is that MC font renderer really doesn't like subscript and superscript. This would make it difficult to render into GUI.

@iLexiconn Using seconds as a measurement might be confusing. Everyone is familiar with the tick standard. It also means more calculating for display of power.

**Comment by Fortanono** [comment]
Makes sense. CW could be the abbreviation.

**Comment by iLexiconn** [comment]
I tought you were creating a _new_ standard

**Comment by Darkhax** [comment]
@iLexiconn That might be true, however I don't think it's a really good idea to alienate everyone like that. It would definitely cause some initial confusion.

**Comment by brandon3055** [comment]
Ok then how about Ah (Amp Hours) which is a measurement of energy storage?

**Comment by Darkhax** [comment]
Okay @brandon3055 but would the mod also be renamed to Ah? Also, the hour part of Ah is a bit of an issue?

**Comment by iLexiconn** [comment]
What about _Glowstone Liquid_?

**Comment by Darkhax** [comment]
@iLexiconn The liquid part is a bit weird. I kind of like the direction of using Light in the name, like l or lux. RedstoneLux :p

**Comment by brandon3055** [comment]
Yea... Im just trying to think of possible energy units that noone  has used... 
Maby just stick with Tesla. It dosnt have to be a thing that makes sense in real life i mean look at redstone flux. And i dont think any of the other mods would have any issues with it because as mentioned they use it as a measurement of magnetic flux not energy.

**Comment by Fortanono** [comment]
Pickamps? (pA)

**Comment by Darkhax** [comment]
I completely agree with you on this @brandon3055. The reason this issue was opened was due to all of the people on reddit who brought up various issues with the idea. Since this is a community project, it is only fair to open it up for public discussion, even if it's not something I personally want. Currently using downvote on the main issue to tally people who are against a name change.

**Comment by rubensworks** [comment]
A radically different option would be to include Tesla into [Common Capabilities](https://github.com/CyclopsMC/CommonCapabilitiesAPI). But I can imagine that you may want to remain independent ;-)

**Comment by p455w0rd** [comment]
JigguhWattz XD

**Comment by Sethgoldfox** [comment]
JiggerWuttz (Not really though XD)

**Comment by SanAndreaP** [comment]
How about Wats?
<img src="http://i.imgur.com/SwfNTmx.jpg" />

Seriously, suggestions I have:
- keep the name, have the unit TeslaWatts (TW/t) or TeslaFlux (TF/t)
- "Dark Units" (DU/t)

that's it, I'm not very creative with fictional unit names :v

**Comment by p455w0rd** [comment]
i like TeslaFlux

**Comment by LatvianModder** [comment]
I like Dark Units

**Comment by Dhvagra** [comment]
The problem with that, SanAndreas, is that RedstoneFlux is derived from, and cables and machines are made with, redstone. TeslaFlux would insinuate it being derived from Tesla-something. So then it'd need an ore and blabla. 

Maybe [Gauss](https://en.wikipedia.org/wiki/Gauss%27s_law)?

> Gauss's law, also known as Gauss's flux theorem, is a law relating the distribution of electric charge to the resulting electric field.

So that would an even bigger nod to real science, and nobody else uses it in any mod right now I believe.

**Comment by p455w0rd** [comment]
thumbs-upping yourself XD totally see your point though and I agree on the TeslaFlux..as far as Dark Units, if @Darkhax is still planning on making PRs to Forge, this would never fly..on that note.. maybe something with 'Forge' in the name

**Comment by Uristqwerty** [comment]
A lot of existing systems have two-letter shortenings: EU, MJ, RF. That would help avoid T/t, at least, even for something as obvious as TU/t.

**Comment by Darkhax** [comment]
I think @Uristqwerty has cracked the code. I am almost 100% satisfied with TU. One potential issue is the higher scales though. KTU, MTU, GTU, PTU and so on. It feels weird to have the other units at three characters.

**Comment by Dhvagra** [comment]
So Gauss would be a good name for prefixes. mG/t, G/t, kG/t, MG/t. (we know from Buckets that this works)

**Comment by gr8pefish** [comment]
I am of the opinion that the display should be in terms of energy/second, not energy/tick. While experienced Minecraft players and coders know the details, abstraction should be used to alleviate the general player from having to understand the inner nuances of the game. Seconds are understood by everyone, whereas ticks are a new term to new players. It could all be done internally in terms of ticks, just displayed in seconds. 

However, I'm not entirely sure how expensive, computationally, it will be to show this. I would assume not too bad, but if it is a real issue then displaying in seconds should be scrapped. Using per second would allow for things like Tt/s to not be nearly as confusing (and currently no major energy system has an 's' abbreviation either).

This is definitely a change, but in the current 1.9 modding environment there is the definite opportunity for such a new standard, and who knows when such a situation will present itself again so favorably?

I also like the two-letter standard notation for energy. One way to possibly help fix the three letter issue with scales is to make the unit be lowercase (i.e. kTU/s or mTU/s) so that it feels more like 2 letters than 3. Not so sure about that though, it still doesn't feel perfect.

**Comment by p455w0rd** [comment]
@gr8pefish - If they're playing modded, chances are they know what ticks are and if they've ever watched any YouTuber/Streamer that plays MC, they likely know that there are 20 ticks for every second. At any rate, this would be decided on the mod's end, not the API.

**Comment by Darkhax** [comment]
@gr8pefish The computational cost of doing it in seconds is not overwhelming and is largely unimportant. However many developers have an aversion to writing needlessly inefficient code. Another issue with using s to solve this issue, is that the rate at which power is displayed is not determined by the API. There are several mods which use the RF API but represent things as seconds, even though everything else uses ticks.

**Comment by Dhvagra** [comment]
It would be easy I guess. Power/tick × tickrate.  
Also, the prefix in lowercase : no. Because m is not the same as M. (Milli vs Mega is a factor million)

By the way : what about something with Power in the name? 
- MachinePower (MP)
- MinecraftPower (MP)
- PowerFlux 
- PowerUnit

**Comment by gr8pefish** [comment]
@p455w0rd , @darkhax Okay, thanks for the clarification. I wasn't entirely sure where it was defined, as I haven't had time to look into the API code in depth yet. 

If you want to change it away from Tesla to something more minecraft-y you could try something like EnderCurrent (EC) or something along those lines. Not sure if you are going for the more realistic or more mystical/abstract.

@Dhvagra, Of course, how did I forget about the lowercase letters. Redacted.

**Comment by ebeneezersquid** [comment]
I think we may have tracked a little off course.

We want another name that is fits the theme of minecraft, is not already a real unit of measurement or a unit used by another power system, and Darkhax orginially named it in honor of Nikola Tesla. 

How about we call the unit "Nikola", or "Nick" for short. 

I don't think that N/T looks bad, nor does kN/T, and saying you have "three hundred Nicks per Tick" kind of rolls off the tongue. 

My $0.02

**Comment by Dhvagra** [comment]
Nikola would be sweet indeed. Though the abbreviation as NK or NL to avoid
confusion with Newtons? Idunno

**Comment by ReikaKalseki** [comment]
I really do not like the idea of it using a real-world unit name when that unit may well be used in other mods for the real purpose, mine or otherwise. All that will accomplish is confusing players and endless spurious reports or pointless questions on both sides.

I am bad at names and therefore, at this time at least, do not have a suggestion of my own, but the important thing is that neither the direct name or its logical /t abbreviation be confusable with something else. This rules out Tesla, Joule, Newton, Watt, Amps, Volts, and Gauss.

Of the proffered names thus far, I kind of like EnderCurrent the best, but I do not see what its unit would be named. Additionally, the "ender" may lead people to assume - or worse, _demand_ - that it work wirelessly.

**Comment by Darkhax** [comment]
Thank you for the input @ReikaKalseki. I really wish I knew about the conflicts between RotaryCraft and Tesla before hand. Would have saved all of us a lot of trouble. 

I think that @Dhvagra and @ebeneezersquid are in the right direction though. N/t is currently the best solution I have seen so far. I will let this discussion go on for a bit longer before putting it up to a final vote.

**Comment by Dhvagra** [comment]
And... if anything... you also could become the new maintainer/dev of the RF API!

**Comment by p455w0rd** [comment]
http://memesvault.com/wp-content/uploads/Hell-Nah-Meme-16.jpg

**Comment by Fortanono** [comment]
How about just "Cubicurrent"? (cC)

**Comment by JCMais** [comment]
**Elektron**

The abbreviation can be just `E` or `EK`, idk.

**Comment by asiekierka** [comment]
Danks. (Dk)

**Comment by loordgek** [comment]
or name it MJ. 
going back old school

**Comment by smbarbour** [comment]
I'm surprised nobody has suggested the blatantly obvious:  Dark Energy

**Comment by N9199** [comment]
EF (Energy Flow)?
EF/t
It may work.

**Comment by Vexatos** [comment]
How about "Energy Units"? I heard generic names like this are fun. :suspect:

**Comment by Eladkay** [comment]
Currently my favorites:
EF for energy flow,
TeslaFlux or TF
T/t not being used, instead using a unit called TeslaTick that measures speed of power gen,
TeslaUnits, as in power of the Tesla system being measured in TeslaUnits

Just my two cents.

**Comment by Vexatos** [comment]
LF - Lapis Flux
PF - Prismarine Flux
GF - Glass Flux
BF - Beacon Flux (Or Bacon Flux)
NF - Netherrack Flux
SF - Sand Flux
AF - Andesite Flux

**Comment by NikkyAI** [comment]
@smbarbour https://github.com/Darkhax-Minecraft/Tesla/issues/4#issuecomment-217435923
there at the bottom

and what you need is something that is
not in any existing (big) minecraft mod
and does not conflict with existing names, so another Redstone.. or ..Flux would not work well (just examples)
also the abbreviation should be unique.. truly complicated

Minecraft Watts (or WATS)
MW

that will eventually lead to confusion with W.. maybe.. but it should be ok

**Comment by Vexatos** [comment]
FF - Fish Flux
PfF - Pufferfish Flux
FFF - Flowing Flux Flux
F - Flux
WF - Walrus Flux
UF - Universal Flux, Useless Flux
RF - Random Flux, Redundant Flux
PF - Pointless Flux
SF - Serious Flux
MF - More Flux
FFLOABN - Flux For Lack Of A Better Name
DF - Dark Flux, Dirt Flux
CF - Cobblestone Flux
GF - Granite Flux
ZF - Zombie Flux

**Comment by loordgek** [comment]
eu is taken by IC2 
i believe EF is taken by Extra Utilities 2
and dont use RF that will be a nightmare to explain to the end user

**Comment by NikkyAI** [comment]
or 
Elektron (E)
Minecraft Elektron (ME)
Elektron Flux (EF)

(ok i am not serious anymore)

**Comment by loordgek** [comment]
PF - Pointless Flux :) that is funny

**Comment by Vexatos** [comment]
CF - Carrot Flux, Construction Foam
PF - Potato Flux
SF - Steak Flux
BF - Beef Flux
DF - Dynamite Flux, Deconstruction Foam
[EF - Electric Flux](https://en.wikipedia.org/wiki/Electric_flux)
[LF - Luminous Flux](https://en.wikipedia.org/wiki/Luminous_flux)
[MF - Magnetic Flux](https://en.wikipedia.org/wiki/Magnetic_flux)
AF - Ambiguous Flux
DF - Disambiguated Flux
OF - Obscrure Flux, Odd Flux
RS - Random Suggestion

I should be done now.

**Comment by smbarbour** [comment]
@Achati Most of the suggestions are on the minutiae of what to call the units, but the original issue is about rebranding the project itself.

**Comment by JCMais** [comment]
@smbarbour I think it's both. In reality more about the unity than the project, the project would just follow the unity it represents.

**Comment by Vexatos** [comment]
EMC - Energy Measurement Consolidation

This should be the most unambiguous of all.

**Comment by heldplayer** [comment]
I for one am fully for WalrusFlux and FlamingoFlux

**Comment by Vexatos** [comment]
FlamingoFlux is mildly heretical, however. WalrusFlux should be sufficient.

**Comment by loordgek** [comment]
EMC - Energy Measurement Consolidation

This should be the most unambiguous of all.

no you get a angry pahimar

**Comment by cout970** [comment]
what about Minecraft Flux or XY Energy?

**Comment by DiMuRie** [comment]
rename to Marie-Curie[@asie] so we can have the abreviation MC/t

**Comment by Vexatos** [comment]
https://en.wikipedia.org/wiki/Curie

**Comment by Fortanono** [comment]
I'm still pushing for Cubicurrent.

**Comment by ReikaKalseki** [comment]
Curies are also a real unit, of radiation.

**Comment by asiekierka** [comment]
Another proposal, from Twitter: Scientifically Accurate Xenon. Or sax, for short. For example: "This machine generates 10 sax per tick."

**Comment by Vexatos** [comment]
@ReikaKalseki Hence my link to the wikipedia article. A deprecated unit but a unit nonetheless.

**Comment by Dhvagra** [comment]
What about faqs then?

**Comment by raoulvdberge** [comment]
Unfortunately sax is ambiguous, it can refer to a saxophone too.

**Comment by asiekierka** [comment]
@Dhvagra That would be a unit better suited to GregTech.

@raoulvdberge

![](http://i.imgur.com/9nohQh4.jpg)

**Comment by ReikaKalseki** [comment]
In general, picking the names of famous scientists is likely to conflict with a real unit, as that is how units tend to be named (including, to my knowledge, all of the ones I listed above). I can think of a few scientists' names that are not used, but I cannot imagine a power system of Sagans or Attenboroughs. :P

**Comment by parcel31u** [comment]
Mmd/t Modded minecraft drama per tick
t/t ticks per tick
Dm/t dank memes per tick
Dd/t Dire derps per tick
Rp/t Rare pepes per tick
Pc/t Power creep per tick

**Comment by DiMuRie** [comment]
hack a` tick sounds gud mateyehh?

**Comment by CyanideX** [comment]
I think "Oomph" is the best power unit; the subunit of Elbow Grease.

**Comment by DiMuRie** [comment]
let`s use STCFlux/SpaceTimeContinuumFlux

**Comment by Darkhax** [comment]
Thank you to everyone for the suggestions. A lot of nice ones, and a few that made me chuckle. Want to give special thanks to @asiekierka for his suggestion, it was very lit. Going to read over all of the suggestions again with the core team of contributors, before making any decisions. A final decision will be made before the 1.0.2 deadline.
