### ISSUE TITLE
Crash on world load / API error

### ISSUE THREAD

**Issue by robaimes** [Darkhax-Minecraft/Tesla#41]
TESLA is not showing up in the list of loaded API's and is causing issues with other mods.

`[bdlib/bdlib]: List of loaded APIs:`
- Relevant snippet from forge log: http://pastebin.com/S8YUPjuh
- Full log: [here](https://dl.dropboxusercontent.com/u/76791645/Downloads/fml-client-latest-2.log)

This is causing issues similar to #40 and [this](http://pastebin.com/PJinvhaM) from [here](https://github.com/mezz/JustEnoughItems/issues/500#issuecomment-251582983)

Using latest Tesla version | `1.2.2.49`

**Comment by canitzp** [comment]
That is because Tesla is no API since Darkhax remove it, but it has a reason.

**Comment by Darkhax** [comment]
The Tesla API does not support API bundling. The API system in forge was created to allow versioned mod bundling.

**Comment by mezz** [comment]
Ok that explains the log, but there is still a strange problem where mods are not finding the capabilities, 
My best guess is that someone has included Tesla in their mod, but without all of the classes? I've seen something like that with RF before.

**Comment by robaimes** [comment]
If it helps, removing EnderIO / EnderCore appears to remedy this issue. While not a solid solution, it may help find the cause.

Here's a forge log with EnderIO and EnderCore removed, which successfully loads the world: https://dl.dropboxusercontent.com/u/76791645/Downloads/fml-client-latest-3.log

**Comment by Darkhax** [comment]
The summary from RF is that one or more mods was attempting to load Tesla before it had been fully constructed. This caused issues which blocked tesla classes from being loaded later down the line. Not sure how accurate that is, but it seems to have solved the issue so I will accept it lol.

**Comment by robaimes** [comment]
¯_(ツ)_/¯
