### ISSUE TITLE
does the TESLA already equals =1EU?

### ISSUE THREAD

**Issue by changemenemo** [Darkhax-Minecraft/Tesla#44]
everything is in the question

**Comment by Prospector** [comment]
TESLA equals 1 RF or FE. 1 EU equals about 11 TESLA.

**Comment by changemenemo** [comment]
so is there any mod since it is an API that transform to tesla the EU?

**Comment by Prospector** [comment]
Yeah, I believe this mod does that https://minecraft.curseforge.com/projects/energysynergy

**Comment by changemenemo** [comment]
great thanks because I didn't want to begin to alterate your code and mess things up:)
