### ISSUE TITLE
Mod Matter Overdrive Won't load with Tesla

### ISSUE THREAD

**Issue by Stryder914** [Darkhax-Minecraft/Tesla#45]
I've tried multiple times to load, but it displays that it requires it, when i have it. Please send me a link to the download for the latest version for 1.10.2, please.

**Comment by RogueLogix** [comment]
https://minecraft.curseforge.com/projects/tesla/files/2327384
Please refer to the Discord server to ask questions like this.

@darkhax make both CurseForge and the Discord server easier for people to find plz.

**Comment by shadowfacts** [comment]
This has been fixed on MO's side, a new version will be released soon.
