### ISSUE TITLE
Amendments to the README file

### ISSUE THREAD

**Issue by Darkhax** [Darkhax-Minecraft/Tesla#8]
**Things to add**
- Explain how soft compatibility can be achieved. 
- Document the standards for the API. 1RF = 1T, should pipes push/pull power

**Preview**

**Comment by adrwa** [comment]
I think the standard for 1Tesla should be 1T->4RF which also happens to be 4RF->1EU, Tesla just seems to suit the EU style a bit more in my opinion.

**Comment by Darkhax** [comment]
For compatibility reasons the 1-1 ratio makes things easier for everyone. Why do you feel it suits the EU style more?

**Comment by adrwa** [comment]
I'm not really sure. Just for some reason in my mind i see Tesla more as something i'd create EU style machines for rather than RF Style.. i don't know if that's the name or the current code.

**Comment by Darkhax** [comment]
Tesla actually takes more after RF than UE in terms of design lol

**Comment by adrwa** [comment]
Yeah, probably after 1.0.2 or 1.0.3 i probably will view it differently. or maybe after it is inevitably renamed Dank
